In [31]:
import pandas as pd
import numpy as np

In [46]:
x = np.arange(1000, 10000)

In [47]:
y = np.arange(1, 100)

In [45]:
all_numbers = np.transpose([np.tile(x, len(y)), np.repeat(y, len(x))])
df = pd.DataFrame(all_numbers)
# df=df[df[0] < df[1]]
df = df.sample(frac=1)[:20000].reset_index(drop=True)

ValueError: a must be greater than 0

In [35]:
# np.random.shuffle(x)
# np.random.shuffle(y)

# df = pd.DataFrame()
# df[0] = x[:10000] 
# df[1] = y[:10000]

In [36]:
df['Question'] = df[0].astype(str) + " / " + df[1].astype(str)

In [37]:
df['Answer'] = df[0] / df[1]

In [38]:
df = df[['Question', 'Answer']]

In [39]:
df.sample(frac=1).to_csv("two_digit_fractions.csv", index=None, header=None)

In [40]:
df

     Question    Answer
0     10 / 44  0.227273
1     27 / 53  0.509434
2     15 / 67  0.223881
3     70 / 85  0.823529
4     52 / 83  0.626506
5     40 / 80  0.500000
6     10 / 63  0.158730
7     39 / 70  0.557143
8      2 / 42  0.047619
9     14 / 16  0.875000
10    22 / 32  0.687500
11    30 / 74  0.405405
12    34 / 38  0.894737
13     2 / 97  0.020619
14    24 / 65  0.369231
15    84 / 98  0.857143
16     2 / 56  0.035714
17     9 / 94  0.095745
18    59 / 80  0.737500
19    64 / 68  0.941176
20     8 / 16  0.500000
21    18 / 82  0.219512
22    24 / 35  0.685714
23     1 / 43  0.023256
24    53 / 76  0.697368
25    27 / 29  0.931034
26    11 / 89  0.123596
27    88 / 97  0.907216
28    66 / 84  0.785714
29    35 / 67  0.522388
...       ...       ...
4821  93 / 98  0.948980
4822   8 / 72  0.111111
4823  76 / 98  0.775510
4824  50 / 72  0.694444
4825   6 / 46  0.130435
4826  18 / 72  0.250000
4827  42 / 89  0.471910
4828   4 / 25  0.160000
4829  54 / 67  0.805970
4830  65 / 81  0.802469
4831  25 / 36  0.694444
4832  39 / 55  0.709091
4833  95 / 96  0.989583
4834  76 / 86  0.883721
4835   4 / 79  0.050633
4836   4 / 83  0.048193
4837  23 / 46  0.500000
4838  17 / 94  0.180851
4839  37 / 81  0.456790
4840  24 / 78  0.307692
4841  47 / 58  0.810345
4842  46 / 62  0.741935
4843  21 / 57  0.368421
4844  45 / 99  0.454545
4845  50 / 73  0.684932
4846   1 / 72  0.013889
4847  55 / 94  0.585106
4848   6 / 10  0.600000
4849  22 / 79  0.278481
4850   9 / 44  0.204545

[4851 rows x 2 columns]

In [ ]:
#now make one for division