In [1]:
import pandas as pd
import numpy as np

In [16]:
x = np.arange(100, 100000)

In [17]:
y = np.arange(100, 100000)

In [20]:
# all_numbers = np.transpose([np.tile(x, len(y)), np.repeat(y, len(x))])
# df = pd.DataFrame(all_numbers)

In [29]:
np.random.shuffle(x)
np.random.shuffle(y)

df = pd.DataFrame()
df[0] = x[:10000] 
df[1] = y[:10000]

In [30]:
df['Question'] = df[0].astype(str) + " × " + df[1].astype(str)

In [31]:
df['Answer'] = df[0] * df[1]

In [32]:
df = df[['Question', 'Answer']]

In [33]:
df.sample(frac=1).to_csv("big_multiplication.csv", index=None, header=None)

In [34]:
df

           Question      Answer
0     73950 × 66340  4905843000
1       763 × 37477    28594951
2     37895 × 37166  1408405570
3     68417 × 60141  4114666797
4     98420 × 44686  4397996120
5      2299 × 85799   197251901
6     65766 × 35441  2330812806
7     75189 × 65201  4902397989
8      24205 × 2449    59278045
9     39112 × 98787  3863757144
10    67106 × 77934  5229839004
11    19667 × 95694  1882013898
12    16126 × 35545   573198670
13    32826 × 76951  2525993526
14    24515 × 37311   914679165
15    91008 × 24889  2265098112
16     38230 × 9094   347663620
17    36700 × 10134   371917800
18    42770 × 18849   806171730
19    59720 × 28204  1684342880
20    89634 × 94302  8452665468
21    35632 × 98217  3499668144
22    45109 × 78199  3527478691
23    73604 × 14596  1074323984
24    36878 × 27175  1002159650
25     5836 × 56546   330002456
26    54929 × 89479  4914991991
27    25174 × 62477  1572795998
28    96202 × 80242  7719440884
29    83705 × 21545  1803424225
...             ...         ...
9970  77018 × 57557  4432925026
9971  19394 × 84217  1633304498
9972   82706 × 9895   818375870
9973  98360 × 59189  5821830040
9974  84155 × 29226  2459514030
9975    5926 × 9624    57031824
9976  83603 × 49453  4134419159
9977  27196 × 21862   594558952
9978  37824 × 37675  1425019200
9979   10874 × 1054    11461196
9980  74360 × 65865  4897721400
9981  42221 × 41201  1739547421
9982  86180 × 50485  4350797300
9983  35651 × 37726  1344969626
9984  46875 × 62728  2940375000
9985  70913 × 21785  1544839705
9986  43786 × 72218  3162137348
9987  89539 × 37277  3337745303
9988  85200 × 54422  4636754400
9989  55989 × 77994  4366806066
9990    85321 × 486    41466006
9991  72044 × 40776  2937666144
9992  80889 × 61625  4984784625
9993   2322 × 50052   116220744
9994    680 × 72897    49569960
9995  96268 × 63898  6151332664
9996  27340 × 85676  2342381840
9997  64533 × 75759  4888955547
9998   55814 × 4203   234586242
9999  69296 × 94178  6526158688

[10000 rows x 2 columns]

In [ ]:
#now make one for division